##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."
  [plugins.inputs]
  suite_id = "netlify-tests"
  wait_for_test_results = true
  # Plugin configuration
  #  [plugins.inputs]
  #  foo = "bar"

[build]
# Dummy build command
command = "echo onBuild"

[build.environment]
NODE_VERSION = "12.20.0"
