##############################
# Netlify configuration file #
##############################

# List of Build plugins
[[plugins]]
# Use the current plugin in builds for testing and debugging.
# Local path to the plugin.
package = "."

[build]
# Dummy build command
command = "echo onBuild"

[build.environment]
NODE_VERSION = "12.20.0"
